"""create_pr builtin — open a pull request via ``gh pr create``."""

from __future__ import annotations

import logging
import re
import tempfile
from pathlib import Path

from darkfactory.operations._registry import builtin
from darkfactory.operations._shared import _log_dry_run, _scan_for_forbidden_attribution
from darkfactory.event_log import emit_builtin_effect
from darkfactory.utils._result import Ok
from darkfactory.utils.github._types import GhErr
from darkfactory.utils.github.pr import create_pr as gh_create_pr
from darkfactory.workflow import ExecutionContext

_log = logging.getLogger(__name__)
_AC_LINE_RE = re.compile(r"^\s*-\s*\[\s*\]\s*(AC-\d+.*)$", re.MULTILINE)


def _extract_acceptance_criteria(body: str) -> list[str]:
    """Pull acceptance criteria lines out of a PRD body.

    Looks for the standard ``- [ ] AC-N: ...`` checkbox format.
    Returns a list of the criterion strings (without the checkbox
    prefix). Used by ``create_pr`` to build the PR body's checklist.
    """
    return [match.group(1).strip() for match in _AC_LINE_RE.finditer(body)]


def _pr_body(ctx: ExecutionContext) -> str:
    """Generate a PR body with a link to the PRD and an AC checklist."""
    prd = ctx.prd
    lines: list[str] = [
        f"Implements `{prd.path.relative_to(ctx.repo_root)}`.",
        "",
    ]

    acs = _extract_acceptance_criteria(prd.body)
    if acs:
        lines.append("## Acceptance criteria")
        lines.append("")
        for ac in acs:
            lines.append(f"- [ ] {ac}")
        lines.append("")

    lines.append("---")
    lines.append(f"Generated by the PRD harness workflow `{ctx.workflow.name}`.")
    return "\n".join(lines)


@builtin("create_pr")
def create_pr(ctx: ExecutionContext) -> None:
    """Open a pull request via ``gh pr create``.

    Title: ``"{prd_id}: {prd_title}"``. Body: generated from the PRD's
    acceptance criteria plus a link to the PRD file. Base branch:
    ``ctx.base_ref``. On success, sets ``ctx.pr_url`` from the URL
    printed by ``gh``. The PRD file must exist at ``ctx.prd.path``
    relative to ``ctx.repo_root``.
    """
    title = f"{ctx.prd.id}: {ctx.prd.title}"
    body = _pr_body(ctx)
    if ctx.run_summary:
        body += "\n\n" + ctx.run_summary
    _scan_for_forbidden_attribution(title, source=f"PR title for {ctx.prd.id}")
    _scan_for_forbidden_attribution(body, source=f"PR body for {ctx.prd.id}")

    if _log_dry_run(
        ctx, f"gh pr create --base {ctx.base_ref} --title {title!r} --body <generated>"
    ):
        ctx.pr_url = "https://example.test/dry-run/pr/0"
        return

    # Write the body to a temp file — passing long bodies via --body
    # can hit argv limits on some systems.
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as body_file:
        body_file.write(body)
        body_path = body_file.name

    try:
        match gh_create_pr(ctx.base_ref, title, body_path, ctx.cwd):
            case Ok(value=url):
                ctx.pr_url = url or None
            case GhErr(returncode=code, stderr=err):
                detail = f"gh pr create failed (exit {code}):\n{err}"
                _log.error(detail)
                raise RuntimeError(detail)
    finally:
        Path(body_path).unlink(missing_ok=True)

    emit_builtin_effect(
        ctx,
        "create_pr",
        "create_pr",
        detail={"pr_url": ctx.pr_url, "base": ctx.base_ref, "title": title},
    )
