"""create_pr builtin — open a pull request via ``gh pr create``."""

from __future__ import annotations

import logging
import re
import tempfile
from pathlib import Path

from darkfactory.engine import CodeEnv, PrRequest, PrdWorkflowRun, WorktreeState
from darkfactory.operations._registry import builtin
from darkfactory.operations._shared import _log_dry_run, _scan_for_forbidden_attribution
from darkfactory.event_log import emit_builtin_effect
from darkfactory.utils import Ok
from darkfactory.utils.github import GhErr
from darkfactory.utils.github.pr import create_pr as gh_create_pr
from darkfactory.workflow import RunContext

_log = logging.getLogger(__name__)
_AC_LINE_RE = re.compile(r"^\s*-\s*\[\s*\]\s*(AC-\d+.*)$", re.MULTILINE)


def _extract_acceptance_criteria(body: str) -> list[str]:
    """Pull acceptance criteria lines out of a PRD body.

    Looks for the standard ``- [ ] AC-N: ...`` checkbox format.
    Returns a list of the criterion strings (without the checkbox
    prefix). Used by ``create_pr`` to build the PR body's checklist.
    """
    return [match.group(1).strip() for match in _AC_LINE_RE.finditer(body)]


def _pr_body_from_prd(ctx: RunContext, prd_run: PrdWorkflowRun) -> str:
    """Generate a PR body with a link to the PRD and an AC checklist."""
    prd = prd_run.prd
    env = ctx.state.get(CodeEnv)
    lines: list[str] = [
        f"Implements `{prd.path.relative_to(env.repo_root)}`.",
        "",
    ]

    acs = _extract_acceptance_criteria(prd.body)
    if acs:
        lines.append("## Acceptance criteria")
        lines.append("")
        for ac in acs:
            lines.append(f"- [ ] {ac}")
        lines.append("")

    lines.append("---")
    lines.append(f"Generated by the PRD harness workflow `{prd_run.workflow.name}`.")
    return "\n".join(lines)


@builtin("create_pr")
def create_pr(
    ctx: RunContext,
    *,
    title: str | None = None,
    body: str | None = None,
) -> None:
    """Open a pull request via ``gh pr create``.

    If ``title``/``body`` kwargs are provided, formats them via
    ``format_string()``. Otherwise, falls back to PrRequest payload
    from state, then to PRD-derived defaults from PrdWorkflowRun.

    On success, stores the PR URL (accessible via result.pr_url from
    the runner).
    """
    wt = ctx.state.get(WorktreeState)
    env = ctx.state.get(CodeEnv)

    # Resolve title and body from kwargs, PrRequest payload, or PRD defaults.
    if title is not None and body is not None:
        resolved_title = ctx.format_string(title)
        resolved_body = ctx.format_string(body)
    elif ctx.state.has(PrRequest):
        pr_req = ctx.state.get(PrRequest)
        resolved_title = ctx.format_string(pr_req.title)
        resolved_body = ctx.format_string(pr_req.body)
    elif ctx.state.has(PrdWorkflowRun):
        prd_run = ctx.state.get(PrdWorkflowRun)
        resolved_title = f"{prd_run.prd.id}: {prd_run.prd.title}"
        resolved_body = _pr_body_from_prd(ctx, prd_run)
        if prd_run.run_summary:
            resolved_body += "\n\n" + prd_run.run_summary
    else:
        raise RuntimeError(
            "create_pr: no title/body kwargs, no PrRequest in state, "
            "and no PrdWorkflowRun in state — cannot determine PR content"
        )

    _scan_for_forbidden_attribution(resolved_title, source="PR title")
    _scan_for_forbidden_attribution(resolved_body, source="PR body")

    if _log_dry_run(
        ctx,
        f"gh pr create --base {wt.base_ref} --title {resolved_title!r} --body <generated>",
    ):
        ctx._pr_url = "https://example.test/dry-run/pr/0"  # type: ignore[attr-defined]
        return

    # Write the body to a temp file — passing long bodies via --body
    # can hit argv limits on some systems.
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as body_file:
        body_file.write(resolved_body)
        body_path = body_file.name

    try:
        match gh_create_pr(wt.base_ref, resolved_title, body_path, env.cwd):
            case Ok(value=url):
                ctx._pr_url = url or None  # type: ignore[attr-defined]
            case GhErr(returncode=code, stderr=err):
                detail = f"gh pr create failed (exit {code}):\n{err}"
                _log.error(detail)
                raise RuntimeError(detail)
    finally:
        Path(body_path).unlink(missing_ok=True)

    emit_builtin_effect(
        ctx,
        "create_pr",
        "create_pr",
        detail={
            "pr_url": getattr(ctx, "_pr_url", None),
            "base": wt.base_ref,
            "title": resolved_title,
        },
    )
