"""Built-in task primitives — real implementations.

Built-ins are the deterministic SDLC operations that every workflow
references by name: create a worktree, set a PRD's status, make a
commit, push a branch, open a PR. They live here (not in individual
workflow modules) because they're shared — every workflow uses the
same ``commit`` primitive, not a bespoke one.

Workflows reference built-ins by name via :class:`~prd_harness.workflow.BuiltIn`::

    BuiltIn("commit", kwargs={"message": "chore(prd): {prd_id} start work"})

The runner looks up ``"commit"`` in :data:`BUILTINS` and calls the
registered function with the :class:`~prd_harness.workflow.ExecutionContext`
plus any formatted kwargs.

**Dry-run mode**: every built-in checks ``ctx.dry_run`` before doing
anything destructive. In dry-run, we log what we WOULD do at INFO
level and return. This is what powers ``prd plan`` and the default
``prd run`` (without ``--execute``).

**Subprocess discipline**: all shell commands use ``subprocess.run``
with an explicit argv list (never ``shell=True``), capture output,
and check the return code. Git and gh invocations go through
:func:`_run_git` and :func:`_run_gh` helpers that centralize cwd
handling and dry-run support.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Callable

from . import prd as prd_module
from .workflow import ExecutionContext, Status

BuiltInFunc = Callable[..., None]
"""Signature every built-in shares: takes ``ExecutionContext`` plus **kwargs, returns None.

Return value is always ``None`` — built-ins communicate results by
mutating the context (setting ``ctx.worktree_path``, ``ctx.pr_url``, etc.)
and signal failure by raising an exception. This keeps the dispatch
uniform in the runner.
"""


BUILTINS: dict[str, BuiltInFunc] = {}
"""Global registry mapping built-in name to its implementing function.

Populated at import time via the :func:`builtin` decorator. The runner
looks up names in this dict when dispatching a
:class:`~prd_harness.workflow.BuiltIn` task. Workflows never touch this
dict directly — they reference built-ins by name only.
"""


def builtin(name: str) -> Callable[[BuiltInFunc], BuiltInFunc]:
    """Decorator that registers a function in :data:`BUILTINS`.

    Rejects duplicate registrations with ``ValueError`` to catch typos
    and accidental overrides during development.
    """

    def decorator(func: BuiltInFunc) -> BuiltInFunc:
        if name in BUILTINS:
            raise ValueError(f"duplicate builtin registration for {name!r}")
        BUILTINS[name] = func
        return func

    return decorator


# ---------- internal helpers ----------


def _run(
    ctx: ExecutionContext,
    cmd: list[str],
    *,
    check: bool = True,
    capture: bool = False,
) -> subprocess.CompletedProcess[str]:
    """Run a subprocess command inside ``ctx.cwd`` with dry-run support.

    In dry-run mode, logs the command at INFO level and returns a fake
    ``CompletedProcess`` with exit code 0. In live mode, runs the
    command for real and raises ``subprocess.CalledProcessError`` on
    non-zero exit when ``check=True``.

    Using an explicit argv list (not a shell string) prevents shell
    injection entirely — callers don't get to interpolate variables
    into a command line, they build the argv themselves.
    """
    if ctx.dry_run:
        ctx.logger.info("[dry-run] %s", " ".join(cmd))
        return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    return subprocess.run(
        cmd,
        cwd=str(ctx.cwd),
        check=check,
        capture_output=capture,
        text=True,
    )


def _worktree_target(ctx: ExecutionContext) -> Path:
    """Compute the worktree path for this PRD under ``.worktrees/``.

    Separated out so tests can assert the path without a whole
    subprocess invocation.
    """
    return ctx.repo_root / ".worktrees" / f"{ctx.prd.id}-{ctx.prd.slug}"


_AC_LINE_RE = re.compile(r"^\s*-\s*\[\s*\]\s*(AC-\d+.*)$", re.MULTILINE)


def _extract_acceptance_criteria(body: str) -> list[str]:
    """Pull acceptance criteria lines out of a PRD body.

    Looks for the standard ``- [ ] AC-N: ...`` checkbox format.
    Returns a list of the criterion strings (without the checkbox
    prefix). Used by ``create_pr`` to build the PR body's checklist.
    """
    return [match.group(1).strip() for match in _AC_LINE_RE.finditer(body)]


def _pr_body(ctx: ExecutionContext) -> str:
    """Generate a PR body with a link to the PRD and an AC checklist."""
    prd = ctx.prd
    lines: list[str] = [
        f"Implements `{prd.path.relative_to(ctx.repo_root)}`.",
        "",
    ]

    acs = _extract_acceptance_criteria(prd.body)
    if acs:
        lines.append("## Acceptance criteria")
        lines.append("")
        for ac in acs:
            lines.append(f"- [ ] {ac}")
        lines.append("")

    lines.append("---")
    lines.append(
        f"Generated by the PRD harness workflow `{ctx.workflow.name}`."
    )
    return "\n".join(lines)


# ---------- built-in implementations ----------


@builtin("ensure_worktree")
def ensure_worktree(ctx: ExecutionContext) -> None:
    """Create (or resume) a git worktree for this PRD.

    Target path: ``{repo_root}/.worktrees/{prd_id}-{slug}``. Branch:
    ``prd/{prd_id}-{slug}`` created from ``ctx.base_ref``. If the
    worktree already exists (previous run resumed), reuses it without
    re-creating. Sets ``ctx.worktree_path`` and ``ctx.cwd`` on success.
    """
    worktree_path = _worktree_target(ctx)
    branch = ctx.branch_name

    if worktree_path.exists() and not ctx.dry_run:
        ctx.logger.info("resuming existing worktree: %s", worktree_path)
        ctx.worktree_path = worktree_path
        ctx.cwd = worktree_path
        return

    # git worktree add -b <branch> <path> <base>
    # Run from the repo root, not from ctx.cwd (which may not be a git dir yet).
    cmd = [
        "git",
        "-C",
        str(ctx.repo_root),
        "worktree",
        "add",
        "-b",
        branch,
        str(worktree_path),
        ctx.base_ref,
    ]
    if ctx.dry_run:
        ctx.logger.info("[dry-run] %s", " ".join(cmd))
    else:
        subprocess.run(cmd, check=True, capture_output=True, text=True)

    ctx.worktree_path = worktree_path
    ctx.cwd = worktree_path


@builtin("set_status")
def set_status(ctx: ExecutionContext, *, to: Status) -> None:
    """Rewrite the PRD's ``status:`` frontmatter field.

    Delegates to :func:`prd_harness.prd.set_status`, which preserves
    the body byte-for-byte and bumps ``updated`` to today. In dry-run
    mode, only logs the intended change.
    """
    if ctx.dry_run:
        ctx.logger.info(
            "[dry-run] set status of %s: %s -> %s",
            ctx.prd.id,
            ctx.prd.status,
            to,
        )
        return

    prd_module.set_status(ctx.prd, to)


@builtin("commit")
def commit(ctx: ExecutionContext, *, message: str) -> None:
    """Stage all changes and make a commit inside the worktree.

    ``message`` is format-string expanded against the context so
    ``"chore(prd): {prd_id} start work"`` becomes
    ``"chore(prd): PRD-070 start work"``. On an empty diff, logs and
    returns without erroring — workflows can safely commit after each
    logical step without worrying about whether anything changed.
    """
    formatted = ctx.format_string(message)

    if ctx.dry_run:
        ctx.logger.info("[dry-run] git add -A && git commit -m %r", formatted)
        return

    # Stage everything
    subprocess.run(
        ["git", "add", "-A"],
        cwd=str(ctx.cwd),
        check=True,
        capture_output=True,
        text=True,
    )

    # Check if there's anything to commit
    diff_result = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        cwd=str(ctx.cwd),
        check=False,
        capture_output=True,
        text=True,
    )
    if diff_result.returncode == 0:
        # No staged changes — skip gracefully.
        ctx.logger.info("commit skipped: no changes to commit")
        return

    # Commit
    subprocess.run(
        ["git", "commit", "-m", formatted],
        cwd=str(ctx.cwd),
        check=True,
        capture_output=True,
        text=True,
    )


@builtin("push_branch")
def push_branch(ctx: ExecutionContext) -> None:
    """Push the current branch to origin with upstream tracking.

    Runs ``git push -u origin {branch}`` inside the worktree. Required
    before :func:`create_pr` because ``gh pr create --base`` needs the
    remote to exist.
    """
    cmd = ["git", "push", "-u", "origin", ctx.branch_name]

    if ctx.dry_run:
        ctx.logger.info("[dry-run] %s", " ".join(cmd))
        return

    subprocess.run(
        cmd,
        cwd=str(ctx.cwd),
        check=True,
        capture_output=True,
        text=True,
    )


@builtin("create_pr")
def create_pr(ctx: ExecutionContext) -> None:
    """Open a pull request via ``gh pr create``.

    Title: ``"{prd_id}: {prd_title}"``. Body: generated from the PRD's
    acceptance criteria plus a link to the PRD file. Base branch:
    ``ctx.base_ref``. On success, sets ``ctx.pr_url`` from the URL
    printed by ``gh``. The PRD file must exist at ``ctx.prd.path``
    relative to ``ctx.repo_root``.
    """
    title = f"{ctx.prd.id}: {ctx.prd.title}"
    body = _pr_body(ctx)

    if ctx.dry_run:
        ctx.logger.info(
            "[dry-run] gh pr create --base %s --title %r --body <generated>",
            ctx.base_ref,
            title,
        )
        ctx.pr_url = "https://example.test/dry-run/pr/0"
        return

    # Write the body to a temp file — passing long bodies via --body
    # can hit argv limits on some systems.
    import tempfile

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as body_file:
        body_file.write(body)
        body_path = body_file.name

    try:
        result = subprocess.run(
            [
                "gh",
                "pr",
                "create",
                "--base",
                ctx.base_ref,
                "--title",
                title,
                "--body-file",
                body_path,
            ],
            cwd=str(ctx.cwd),
            check=True,
            capture_output=True,
            text=True,
        )
    finally:
        Path(body_path).unlink(missing_ok=True)

    # gh prints the PR URL to stdout on success.
    url_line = result.stdout.strip().splitlines()[-1] if result.stdout.strip() else ""
    ctx.pr_url = url_line or None


@builtin("cleanup_worktree")
def cleanup_worktree(ctx: ExecutionContext) -> None:
    """Remove the worktree after a successful run.

    Idempotent — if the worktree is already gone, logs and returns.
    Normally skipped during chain execution so downstream worktrees
    can base on this branch; called explicitly via ``prd cleanup``
    after the whole chain is done.
    """
    if ctx.worktree_path is None:
        ctx.logger.info("cleanup_worktree: no worktree path set, skipping")
        return

    if not ctx.worktree_path.exists():
        ctx.logger.info(
            "cleanup_worktree: %s already gone, skipping", ctx.worktree_path
        )
        return

    cmd = [
        "git",
        "-C",
        str(ctx.repo_root),
        "worktree",
        "remove",
        str(ctx.worktree_path),
    ]

    if ctx.dry_run:
        ctx.logger.info("[dry-run] %s", " ".join(cmd))
        return

    subprocess.run(cmd, check=True, capture_output=True, text=True)
