"""Built-in task primitives — re-export hub.

Imports every submodule so @builtin-decorated functions register on
package import. Re-exports the public API for backwards compatibility.

Built-ins are the deterministic SDLC operations that every workflow
references by name: create a worktree, set a PRD's status, make a
commit, push a branch, open a PR. They live here (not in individual
workflow modules) because they're shared — every workflow uses the
same ``commit`` primitive, not a bespoke one.

Workflows reference built-ins by name via :class:`~darkfactory.workflow.BuiltIn`::

    BuiltIn("commit", kwargs={"message": "chore(prd): {prd_id} start work"})

The runner looks up ``"commit"`` in :data:`BUILTINS` and calls the
registered function with the :class:`~darkfactory.workflow.ExecutionContext`
plus any formatted kwargs.

**Dry-run mode**: every built-in checks ``ctx.dry_run`` before doing
anything destructive. In dry-run, we log what we WOULD do at INFO
level and return. This is what powers ``prd plan`` and the default
``prd run`` (without ``--execute``).

**Subprocess discipline**: all shell commands use ``subprocess.run``
with an explicit argv list (never ``shell=True``), capture output,
and check the return code. Git and gh invocations go through
:func:`_run_git` and :func:`_run_gh` helpers that centralize cwd
handling and dry-run support.
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path

from darkfactory.builtins._registry import BUILTINS, BuiltInFunc, builtin
from darkfactory.builtins._shared import (
    _FORBIDDEN_ATTRIBUTION_PATTERNS,
    _run,
    _scan_for_forbidden_attribution,
)
from darkfactory.builtins.set_status import set_status  # noqa: F401
from darkfactory.workflow import ExecutionContext

_log = logging.getLogger(__name__)

# Import submodules to trigger @builtin registration.
from darkfactory.builtins.commit import commit  # noqa: E402
from darkfactory.builtins.commit_transcript import commit_transcript  # noqa: E402
from darkfactory.builtins.ensure_worktree import ensure_worktree  # noqa: E402
from darkfactory.builtins.push_branch import push_branch  # noqa: E402
from darkfactory.builtins.summarize_agent_run import summarize_agent_run  # noqa: E402

__all__ = [
    "BUILTINS",
    "BuiltInFunc",
    "builtin",
    "_run",
    "_scan_for_forbidden_attribution",
    "_FORBIDDEN_ATTRIBUTION_PATTERNS",
    "ensure_worktree",
    "set_status",
    "commit",
    "push_branch",
    "summarize_agent_run",
    "commit_transcript",
    "create_pr",
    "lint_attribution",
    "cleanup_worktree",
]


_AC_LINE_RE = re.compile(r"^\s*-\s*\[\s*\]\s*(AC-\d+.*)$", re.MULTILINE)


def _extract_acceptance_criteria(body: str) -> list[str]:
    """Pull acceptance criteria lines out of a PRD body.

    Looks for the standard ``- [ ] AC-N: ...`` checkbox format.
    Returns a list of the criterion strings (without the checkbox
    prefix). Used by ``create_pr`` to build the PR body's checklist.
    """
    return [match.group(1).strip() for match in _AC_LINE_RE.finditer(body)]


def _pr_body(ctx: ExecutionContext) -> str:
    """Generate a PR body with a link to the PRD and an AC checklist."""
    prd = ctx.prd
    lines: list[str] = [
        f"Implements `{prd.path.relative_to(ctx.repo_root)}`.",
        "",
    ]

    acs = _extract_acceptance_criteria(prd.body)
    if acs:
        lines.append("## Acceptance criteria")
        lines.append("")
        for ac in acs:
            lines.append(f"- [ ] {ac}")
        lines.append("")

    lines.append("---")
    lines.append(f"Generated by the PRD harness workflow `{ctx.workflow.name}`.")
    return "\n".join(lines)


# ---------- built-in implementations ----------


def _format_tool_counts(tool_counts: dict[str, int]) -> str:
    """Format tool counts as a compact inline string, e.g. 'Read×5, Edit×3'."""
    if not tool_counts:
        return "none"
    return ", ".join(f"{name}×{count}" for name, count in sorted(tool_counts.items()))


def _format_invocations(ctx: ExecutionContext) -> str:
    """Format agent invocation count from context."""
    count = ctx.invoke_count
    if count == 0:
        return "0"
    if count == 1:
        return "1"
    return str(count)
  

@builtin("create_pr")
def create_pr(ctx: ExecutionContext) -> None:
    """Open a pull request via ``gh pr create``.

    Title: ``"{prd_id}: {prd_title}"``. Body: generated from the PRD's
    acceptance criteria plus a link to the PRD file. Base branch:
    ``ctx.base_ref``. On success, sets ``ctx.pr_url`` from the URL
    printed by ``gh``. The PRD file must exist at ``ctx.prd.path``
    relative to ``ctx.repo_root``.
    """
    title = f"{ctx.prd.id}: {ctx.prd.title}"
    body = _pr_body(ctx)
    if ctx.run_summary:
        body += "\n\n" + ctx.run_summary
    _scan_for_forbidden_attribution(title, source=f"PR title for {ctx.prd.id}")
    _scan_for_forbidden_attribution(body, source=f"PR body for {ctx.prd.id}")

    if ctx.dry_run:
        ctx.logger.info(
            "[dry-run] gh pr create --base %s --title %r --body <generated>",
            ctx.base_ref,
            title,
        )
        ctx.pr_url = "https://example.test/dry-run/pr/0"
        return

    # Write the body to a temp file — passing long bodies via --body
    # can hit argv limits on some systems.
    import tempfile

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as body_file:
        body_file.write(body)
        body_path = body_file.name

    try:
        result = subprocess.run(
            [
                "gh",
                "pr",
                "create",
                "--base",
                ctx.base_ref,
                "--title",
                title,
                "--body-file",
                body_path,
            ],
            cwd=str(ctx.cwd),
            check=True,
            capture_output=True,
            text=True,
        )
    finally:
        Path(body_path).unlink(missing_ok=True)

    # gh prints the PR URL to stdout on success.
    url_line = result.stdout.strip().splitlines()[-1] if result.stdout.strip() else ""
    ctx.pr_url = url_line or None


@builtin("lint_attribution")
def lint_attribution(ctx: ExecutionContext) -> None:
    """Fail if any commit on the branch or the run summary credits Claude/Anthropic.

    Scans:

    - Every commit message in ``{base_ref}..HEAD`` on the current branch
    - ``ctx.run_summary`` (which feeds the PR body)

    Intended to run after the agent + verification phases and before
    ``push_branch`` / ``create_pr``, so violations abort the workflow
    before anything lands on the remote or in a PR. Dry-run is a no-op
    because there are no real commits to scan.
    """
    if ctx.dry_run:
        ctx.logger.info("[dry-run] lint_attribution: skipped")
        return

    _scan_for_forbidden_attribution(
        ctx.run_summary or "", source=f"run summary for {ctx.prd.id}"
    )

    result = subprocess.run(
        ["git", "log", f"{ctx.base_ref}..HEAD", "--format=%H%x00%B%x1e"],
        cwd=str(ctx.cwd),
        check=True,
        capture_output=True,
        text=True,
    )
    # Record separator \x1e between commits; field separator \x00 between
    # sha and body. Keeps us robust against newlines in commit messages.
    for entry in result.stdout.split("\x1e"):
        entry = entry.strip()
        if not entry:
            continue
        sha, _, body = entry.partition("\x00")
        _scan_for_forbidden_attribution(
            body, source=f"commit {sha[:12]} on {ctx.branch_name}"
        )

    ctx.logger.info("lint_attribution: clean")


@builtin("cleanup_worktree")
def cleanup_worktree(ctx: ExecutionContext) -> None:
    """Remove the worktree after a successful run.

    Idempotent — if the worktree is already gone, logs and returns.
    Normally skipped during chain execution so downstream worktrees
    can base on this branch; called explicitly via ``prd cleanup``
    after the whole chain is done.
    """
    if ctx.worktree_path is None:
        ctx.logger.info("cleanup_worktree: no worktree path set, skipping")
        return

    if not ctx.worktree_path.exists():
        ctx.logger.info(
            "cleanup_worktree: %s already gone, skipping", ctx.worktree_path
        )
        return

    cmd = [
        "git",
        "-C",
        str(ctx.repo_root),
        "worktree",
        "remove",
        str(ctx.worktree_path),
    ]

    if ctx.dry_run:
        ctx.logger.info("[dry-run] %s", " ".join(cmd))
        return

    subprocess.run(cmd, check=True, capture_output=True, text=True)
